services:
  nextjs:
    container_name: nextjs
    image: ghcr.io/traipoap/nextjs:latest
    build:
      context: .
    expose:
      - 3000
    networks:
      - proxy

networks:
  proxy:
    external: true